const globals = {
  Array: 'readonly',
  Blob: 'readonly',
  DataView: 'readonly',
  Error: 'readonly',
  Infinity: 'readonly',
  JSON: 'readonly',
  Map: 'readonly',
  Math: 'readonly',
  Number: 'readonly',
  Object: 'readonly',
  Option: 'readonly',
  Promise: 'readonly',
  ResizeObserver: 'readonly',
  Set: 'readonly',
  String: 'readonly',
  TextDecoder: 'readonly',
  TextEncoder: 'readonly',
  Uint8Array: 'readonly',
  URL: 'readonly',
  console: 'readonly',
  devicePixelRatio: 'readonly',
  document: 'readonly',
  globalThis: 'readonly',
  parseInt: 'readonly',
  requestAnimationFrame: 'readonly',
  structuredClone: 'readonly',
  window: 'readonly',
};

export default [
  {
    ignores: ['site/vendor/**'],
  },
  {
    files: ['site/**/*.js', 'site/**/*.mjs'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals,
    },
    rules: {
      'no-constant-binary-expression': 'error',
      'no-dupe-keys': 'error',
      'no-redeclare': 'error',
      'no-unreachable': 'error',
      'no-var': 'error',
    },
  },
  {
    files: ['scripts/**/*.mjs'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals,
        Buffer: 'readonly',
        Event: 'readonly',
        HTMLCanvasElement: 'readonly',
        KeyboardEvent: 'readonly',
        MouseEvent: 'readonly',
        PointerEvent: 'readonly',
        Worker: 'readonly',
        cancelAnimationFrame: 'readonly',
        clearTimeout: 'readonly',
        createImageBitmap: 'readonly',
        fetch: 'readonly',
        getComputedStyle: 'readonly',
        indexedDB: 'readonly',
        innerHeight: 'readonly',
        innerWidth: 'readonly',
        localStorage: 'readonly',
        location: 'readonly',
        navigator: 'readonly',
        performance: 'readonly',
        process: 'readonly',
        sessionStorage: 'readonly',
        setTimeout: 'readonly',
      },
    },
    rules: {
      'no-undef': 'error',
      'no-unused-vars': ['error', { args: 'none', caughtErrors: 'none', ignoreRestSiblings: true }],
      'no-constant-binary-expression': 'error',
      'no-dupe-keys': 'error',
      'no-redeclare': 'error',
      'no-unreachable': 'error',
      'no-var': 'error',
    },
  },
];
